### ISSUE TITLE
[question] how to get a row count?

### ISSUE THREAD

**Issue by ketzacoatl** [justwatchcom/sql_exporter#1]
Hello!

I have setup your exporter with prometheus and postgres, and I can see basic metrics being exported using the config provided in the repo. However, when I go to write my own queries, I am not understanding how this is done. I started with a few simple examples:

```
  - name: "msg_count"
    help: "Number of messages in the posts table"
    values:
      - "msg_count"
    query: "SELECT COUNT(*) FROM posts;"
```

```
  - name: "connections"
    help: "Active Connections"
    values:
      - "connections_count"
    query: "SELECT sum(numbackends) FROM pg_stat_database;"
```

The logs look ok, and I can query prometheus for the stats, though they come back 0 (I can see correct values with `psql`, so I know 0 is wrong).

I assume that I don't have the config correct, but I haven't been able to figure out what I'm doing wrong.

**Comment by dominikschulz** [comment]
Thanks for giving this exporter a try. We're preparing some more docs that will make things a little clearer.

The important detail here is, that the exporter looks for columns matching the names in the "values" array.

This should work:
```
  - name: "msg_count"
    help: "Number of messages in the posts table"
    values:
      - "msg_count"
    query: "SELECT COUNT(*) AS msg_count FROM posts;"
```

I.e. you need to alias your value columns if they don't have a _valid_ SQL name already.
