### ISSUE TITLE
timestamp parameter not working

### ISSUE THREAD

**Issue by syndic8-joe** [justwatchcom/sql_exporter#147]
Hey Folks,

Thanks for this, in general we've been using this in production for years and it's great! As we get more advanced, I have a query where I'm trying to make use of the `timestamp` feature, such that the `BatchStartDate` will be used as the timestamp of the metric event, but it seems to not be working (the metrics all come over with `now()` as the time, as is the typical default behavior). Perhaps I'm not understanding how this is meant to work; an open question is what happens as the values change if the timestamp is fixed (as would be the case in our usage - the labels and values will change for the same metric over time).

I checked the pod logs and there are no errors; the query executes without issue and produces the expected results (minus a "back-dating" of the timestamps).

The config looks like:
```
      - name: "batch_loads"
        help: 'None.'
        timestamp: "BatchStartDate"
        labels:
          - BatchStatus
          - ProcessType
          - TotalCount
          - TotalPass
          - TotalErrors
          - BatchStartDate
          - BatchEndDate
        values:
          - TotalCount
        query:  |
          select BatchStartDate, BatchEndDate, ...
```

This is reading from a load statistics table and I want to use grafana alerting / date filtering based on the batch date.

Any ideas?
