### ISSUE TITLE
Support for multiple configuration files

### ISSUE THREAD

**Issue by aivanov-citc** [justwatchcom/sql_exporter#58]
It would be nice to be able to add multiple configuration files. Then it will be possible to store these configs together with the configuration of the database from which the metrics are collected.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-exporter
spec:
...
  containers:
    - name: sql-exporter
      env:
        - name: CONFIG_FOLDER
            value: /config
...
          volumeMounts:
          - mountPath: /config
            name: config-volume
  volumes:
    - name: config-volume
      configMap:
        name: sql-exporter-config
 ...
```
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
...
configMapGenerator:
- name: sql-exporter-config
  files:
  - config1.yaml
  - config2.yaml
 ...
```
