### ISSUE TITLE
Clickhouse http connection support

### ISSUE THREAD

**Issue by Hubbitus** [justwatchcom/sql_exporter#79]
Hello.

I am trying to run exporter with clickhouse, my simple config:
```yaml
---
jobs:
  - name: "global"
    interval: '5s'
    connections:
      - 'clickhouse://admin:******@10.221.0.19:31673'
    queries:
      - name: "custom_cluster_nodes_count"
        help: "Amount of cluster nodes"
        labels:
          - "cluster"
          - "region"
        values:
          - "amount"
        query:  |
                SELECT 'cluster' as cluster, 'region' as region, COUNT(*) as amount FROM system.clusters
```

But in logs got:
```
{"caller":"job.go:190","err":"read tcp 10.0.2.100:60136->10.221.0.19:31673: i/o timeout","job":"global","level":"warn","msg":"Failed to connect","ts":"2023-06-19T08:42:30.770058746Z"}
{"caller":"job.go:190","err":"read tcp 10.0.2.100:59498->10.221.0.19:31673: i/o timeout","job":"global","level":"warn","msg":"Failed to connect","ts":"2023-06-19T08:42:32.334186815Z"}
```

I've tried use DSN like `clickhouse+http://admin:******@10.221.0.19:31673` (by https://github.com/xo/dburl doc), but also without success:

```
{"caller":"job.go:190","err":"sql: unknown driver \"clickhouse+http\" (forgotten import?)","job":"global","level":"warn","msg":"Failed to connect","ts":"2023-06-19T08:43:45.063663853Z"}
```

But official [clickhouse-go driver also has http support](https://github.com/ClickHouse/clickhouse-go#http-support-experimental).

How I should configure using `http` instead of `tcp` in connection?
